# Generated by Django 5.2.15 on 2026-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inquiry_only",
            field=models.BooleanField(default=False),
        ),
    ]
